### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by TeXitoi** [comment]
In theory, that's a breaking change as it will not compile on older compilers. But who care, `dyn` is quite old and I don't have a rustc version policy for the moment.

So, minor version or major?

**Comment by GuillaumeGomez** [comment]
Minor please. :)

**Comment by TeXitoi** [comment]
`dyn` is from 1.27 one year ago, so let's do that in a minor release.

**Comment by TeXitoi** [comment]
v0.13.1 published

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
