### PR TITLE
Update flat map

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
fixes #28 #27

### CODE REVIEW

**Comment by TeXitoi** [comment]
So we can close #28 and #27 ?

**Comment by GuillaumeGomez** [comment]
You have the choice so up to you. ;)

**Comment by TeXitoi** [comment]
v0.13.4 published

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by TeXitoi** [comment]
Welcome :-)

**Pull request merged**
