### PR TITLE
Test borrowed_iter

### LINKED ISSUE #4: Add compile-fail tests
As described here, http://erickt.github.io/blog/2015/09/22/if-you-use-unsafe/

### PR DESCRIPTION
**Pull request by pczarn**
fix #4

### CODE REVIEW

**Comment by TeXitoi** [comment]
Thanks. Do you know how I can run it with travis only on nightly?

For me, your notes on IRC:
* fn borrowed_iter should be a method on BorrowedIter, maybe called fn new -> Noted
* this belongs in rust-itertools, if it's safe -> Noted, I'll try to propose something like that there.
* change the order of arguments from (closure, value) to (value, closure) -- even option.map_or has the latter order -> argeed, I'll do it
* consider using IntoIterator instead of a closure -> I think it'll be less flexible. For instance, `PrimitiveBlock` is a protobuf generated type, which may not be provided by my crate.

Thanks again!

**Comment by pczarn** [comment]
It can run with travis-cargo, add to `.travis.yml`
```
env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
```

**Comment by pczarn** [comment]
Or... I should have just named the feature "unstable"

**Comment by TeXitoi** [comment]
Damn, the test compiles :( https://travis-ci.org/TeXitoi/osmpbfreader-rs/jobs/121433792

**Pull request merged**
